### ISSUE TITLE
using semver

### ISSUE THREAD

**Issue by oriSomething** [ParsePlatform/Parse-SDK-JS#14]
since in the version `1.6.x` there were intreduce so many breaking changing it would be appropriate to bump to ver `2.0.0`.
those breaking changes can make lots of code breaks for `NPM` users

edit: also using tags of release in this repository can be very helpful

**Comment by andrewimm** [comment]
Our response can be found here: https://groups.google.com/forum/#!msg/parse-developers/zm4o3glBa-o/NXv5oaGbCQAJ

"We didn't make this decision lightly. A survey of developers found that the Backbone features (chiefly, events and collections) were rarely used, often because they were no longer compatible with recent releases of Backbone. Following the upcoming open sourcing of the SDK, we hope that discussions with the larger developer community will determine whether we should release an official Parse+Backbone binding library, or foster a community-driven effort that could be maintained in tandem with Backbone API changes."
"Generally, our SDKs don't follow SEMVER religiously. We use patch numbers for bug fixes, and minor numbers for new features and light behavioral changes. We save major increments for dramatic API changes, and that's not something we've had yet. 2.0 would be reserved for a truly major change. I understand that npm is more focused on SEMVER ranges, but we try to be consistent with our versioning across all platforms. We removed some deprecated functionality, but the rest of the SDK behaves exactly as it did in 1.5."

The only public API changes between 1.5 and 1.6 were to remove outdated implementations of Backbone functionality that we decided were safe to remove. The majority of apps should not have any friction upgrading to 1.6 and above.
That being said, releasing applications with SEMVER ranges in dependencies seems like unsafe behavior. Even patch versions may introduce unexpected changes, so dependencies for an application should be explicitly tied to specific versions. Npm-shrinkwrapping is also a good practice when deploying libraries or applications to production.
