### ISSUE TITLE
Use ACL's on Node

### ISSUE THREAD

**Issue by jesperbruunhansen** [ParsePlatform/Parse-SDK-JS#172]
I have successfully created Roles in Parse and added these to my Objects ACL. I have added a couple of users to my Role, and are successfully retrieving the expected objects, when querying from my client (after log-in with the user).

Now, when moving this functionality to my server environment (Node.js on Heroku, connected to Parse Webhooks), the query *does not return the same result*, since is does not return any objects.

I guessed to cause of this problem, was due to the fact, that the server is "current user"-stateless, and thus not knowing what user to query the class with.

I managed to get my expected results back again, when running
```
Parse.User.enableUnsafeCurrentUser()
Parse.User.become(request.user.getSessionToken()).then(function(user){
  //call query
});
```
... which works!

I'm not a fan of setting the `Parse.User` in a global context on the server, since it brings the server into state. 

My question is now - is there another, much smarter way of doing this?
I would like to avoid using `Parse.User.become(...)`, but my queries still has to be able to know which user has made the query in order to enforce the ACL.

Thank you in advance, 
Jesper

**Comment by andrewimm** [comment]
You're right, setting the current user in a shared-memory environment is unsafe. That's why we allow you to call any arbitrary server action with the session token you need, just like you can call any action with the master key.

```js
// run a query with no session token
new Parse.Query('Item').find();

// run a query with a session token
new Parse.Query('Item').find({ sessionToken: 'MY_SESSION_TOKEN' });
```

You can find more in the [API docs](http://parse.com/docs/js/api/classes/Parse.Query.html#methods_find). This option is available on most commands that can be affected by the current user (pretty much everything except for Analytics, Config, and Push).

**Comment by jesperbruunhansen** [comment]
Hi @andrewimm - thanks for a quick answer!
That was exactly what I was looking for, perfect!

Jesper.
