### ISSUE TITLE
Unable to import sdk via jspm cdn

### ISSUE THREAD

**Issue by abhishiv** [ParsePlatform/Parse-SDK-JS#182]
I was trying to use npm:parse with jspm, and it seems that it works only via command line. While using it directly in the browser via jspm CDN, it tries to pull in https://registry.jspm.io/parse/node.js which results in 404. From the original PR it seems it should be pulling in parse-latest.js instead. 

The original override was created in jspm/registry#609

Test case here - http://s.codepen.io/abhishiv/debug/RrZyWL
Source here - http://codepen.io/abhishiv/pen/RrZyWL

I also opened up an issue in jspm registry jspm/registry#716, but i'm not sure where the problem lies - jspm registry or package.json. I do remember using it via jspm cdn last year and it worked fine then.

**Comment by andrewimm** [comment]
You should follow up on the jspm repo, since nothing has changed with the directory structure here. Our jspm registry entry was done as a courtesy, but it's not officially supported by Parse. Our only official distribution channels are through npm, parse.com downloads, www.parsecdn.com, and the releases on this GitHub repo.

**Comment by typhonrt** [comment]
@abhishiv follow up on the JSPM CLI repo for the CDN question if you haven't already. I haven't used JSPM in that way before, so it could be a non-related issue to Parse.

I am consuming the Parse browser SDK just fine with normal JSPM / SystemJS installation and usage.
