### ISSUE TITLE
Typings for parse

### ISSUE THREAD

**Issue by aayushkapoor206** [ParsePlatform/Parse-SDK-JS#252]
There are no latest typings available for parse in ES6 module format. Can't import parse without declaring it as global using es6

**Comment by andrewimm** [comment]
Can you provide an example? `import * as Parse from 'parse'`; or `import {Parse} from 'parse';` both work for me.

**Comment by aayushkapoor206** [comment]
I get the error: Module '"parse"' resolves to a non-module entity and cannot be imported using this construct.

**Comment by andrewimm** [comment]
Sorry, let me clarify. Can you provide an example of code that reliably produces this error?

Also, if you can, provide the version number of the Parse SDK, as well as any information on your build tools and environment (webpack, browserify, rollup, react native, etc)

**Comment by aayushkapoor206** [comment]
After `typings install parse --ambient --save`, when I try to import it in any typescript file using `import * as Parse from 'parse';` or `import {Parse} from 'parse';`, I get this error. I installed the latest available package using `npm install --save parse`

**Comment by andrewimm** [comment]
From what I can tell, the SDK doesn't currently match the expectations that Typescript has for ES6 modules, which is arbitrary anyways because we're dealing with ES6 compiled down to ES5. I'll investigate ways to make this work better with TS, but in the meantime you should be able to avoid this by simply writing
`const Parse = require('parse')`

**Comment by aayushkapoor206** [comment]
@andrewimm Thanks, solved it. I can't use require statements, so I'm just loading it globally in the browser atm.

**Comment by flavordaaave** [comment]
#224

**Comment by flavordaaave** [comment]
#224

I still can't resolve the TS error.

```
import {Parse} from 'parse';
```
code is working but I get the already mentioned error:  `Module '"parse"' resolves to a non-module entity and cannot be imported using this construct.`

```
import Parse = require('parse');
```
Works but then I need to use `Parse.Parse.initialize` in my code.

```
import Parse = require('parse').Parse;
```
is not working

```
const Parse = require('parse')
```
is not working. Error `Cannot find name 'require'`

Since my project is growing each day with more and more parse imports I really would appreciate if the SDK would work with the standard TS import syntax.

**Comment by aayushkapoor206** [comment]
@flavordaaave You need to add typings for node as well... Add jquery and underscore too because parse requires it...

**Comment by flavordaaave** [comment]
@aayushkapoor206 I already have the definitions for node, jquery and underscore installed but still I get TS complaining about my import statement...

**Comment by doender** [comment]
@flavordaaave I'm running into the same issues. Did you ever get to solve it?

**Comment by flavordaaave** [comment]
@doender only the ugly way with `const Parse = require('parse');` is working for me. At least after a quick test.

**Comment by doender** [comment]
@flavordaaave I stumbled upon the following 'solution':
```
import parse = require('parse');
let Parse = parse.Parse;
```

Although the typings definition I found was not up-to-date (v1.2.19) and I had to modify it somewhat (add `static registerSubclass(className: string, object:any): any;`) to be able to extend Parse.Object with getters/setters.
