### ISSUE TITLE
Support useMasterKey option in Parse.FacebookUtils.Link

### ISSUE THREAD

**Issue by steven-supersolid** [ParsePlatform/Parse-SDK-JS#260]
Currently it is possible to link with Facebook on Parse.com-hosted Cloud Code. It is not possible on parse-server because there is no currentUser. If the useMastkerKey option was supported then this would be possible.

I think the problem lies with ParseUser.linkWith only accepting and calling user.save with an authData parameter, whereas it should accept and use the full options object.

For reference, here is the discussion in parse-server
https://github.com/ParsePlatform/parse-server/issues/1464

**Comment by andrewimm** [comment]
For now, I don't feel comfortable changing the API of linkWith / auth providers. FB linking on the server is already a gray area, since it doesn't actually use the provider. You're only using the secondary effect, which is to attach the already-produced permissions to a Parse.User object.

It seems to me that you could accomplish the same goals, without going through all the codepaths designed for the client, with the following:

```js
// assuming some user `u` and a permissions object `permissions`
let authData = u.get('authData') || {};
authData.facebook = permissions;
u.save({ authData: authData }).then(() => {
  // auth data added
});
```

**Comment by steven-supersolid** [comment]
That's great and really simplifies things. For some reason I didn't think authData could be modified, wish I'd done it this way originally!

**Comment by natario1** [comment]
@andrewimm I have a question about your suggestion (modifying authData instead of using linkWith).

If I try to link the standard way and that provider’s account is already linked to another parse user, I get the precious error 208, account already linked. Would that still apply with your suggestion, or is it part of the _client codepaths_ that we are avoiding?

If so, do you have suggestions on how to check this before attaching the same authData to a second user?

Thank you.
