### ISSUE TITLE
Extend class props with Parse.Object.extend()

### ISSUE THREAD

**Issue by peeinears** [ParsePlatform/Parse-SDK-JS#268]
**This is a feature request/proposal.**

It would be cool if class props were passed down to extended objects via `Parse.Object.extend()`.

For example:

```javascript
var BaseObject = Parse.Object.extend('__BaseObject__', {}, {

  // class props

  query: function () {
    return new Parse.Query(this.className);
  },

  count: function () {
    return this.query().count();
  }

});

var User = BaseObject.extend('User');

User.count().then(function (count) {
  console.log('There are ' + count + ' users');
});
```

Thoughts?

**Comment by andrewimm** [comment]
Unfortunately, there are a number of reasons why we'll probably never do this.

In the theory OOP inheritance, it's potentially unsafe to automatically inherit all statics from the parent, since they may not be relevant to the current class, or they may attempt to use other behaviors that have changed.

In JS's prototypal inheritance, this changes a little, but the concepts are the same. And since we're encouraging developers to move away from the legacy `.extend()` method, towards true ES6 `class`es which don't support static inheritance by default, it wouldn't be a great developer experience to add another feature that acts differently from the direction the language itself is moving.
If anything, JS makes it easier to make mistakes here, since now you have to guarantee that your method is being called with the proper context. In my personal opinion, `SomeObject.count()` should be rewritten as `count(SomeObject)` (ignoring naming and namespaces for a moment), which removes any ambiguity around context.

If you really wanted to achieve something like this, you can reference the parent's class like so:

```js
query: function() {
  return this.__super__.query();
}
```

Heck, you could even use this to add your own extends-like method which automatically applies the the parent's static methods. Though, even in that scenario, I'd encourage explicitly-provided methods over automatically inheriting everything.

```js
function customExtend(base, className, instanceMethods, classMethods) {
  // Include the ones I always want to provide
  var allClassMethods = {
    query: ...
    count: ...
  };
  if (classMethods) {
    for (var c in classMethods) {
      allClassMethods[c] = classMethods[c];
    }
  }
  return base.extend(className, instanceMethods, allClassMethods);
}
```

Hope that all makes sense!

**Comment by peeinears** [comment]
@andrewimm Ah, that makes total sense. I hugely appreciate the explanation! Thank you.
