### ISSUE TITLE
Extending Parse.User gets really weird behaviour

### ISSUE THREAD

**Issue by jcguarinpenaranda** [ParsePlatform/Parse-SDK-JS#281]
Hello,

Today our team discovered that extending Parse.User gives a weird behaviour. The following is the abstraction of the logic we have in our application:

```javascript

var Animal = Parse.User.extend({},{})
var Mammal = Animal.extend({},{})
var Cat = Mammal.extend({},{})
var Dog = Mammal.extend({},{})

var p = new Dog()

p instanceof Cat
// gives true O_O
```
As you can see, p is an instance of a Cat, and for us there is no reason why

**Comment by andrewimm** [comment]
This is expected behavior. When you extend a subclass of Parse.Object (such as Parse.User), you modify the existing prototype and statics. This is because you cannot have two different constructors tied to the same Class Name. If you could, how would the SDK know which constructor to use when it receives an object from the server?

In more detail,

```js
var Animal = Parse.Object.extend('Animal');
var Mammal = Animal.extend({...}, {...});
// Mammal.className is also 'Animal'

new Parse.Query('Animal').find().then((objects) => {
  // If Animal and Mammal were different constructors, which one was used to construct "objects"
});
```

Here's an annotated example of what's happening under the hood:
```js
// Parse.User is already a special subclass of Parse.Object, with className === '_User'

// Adds new instance and static properties to Parse.User
// Animal === Parse.User
var Animal = Parse.User.extend({},{})

// Adds even more instance and static properties to Parse.User
// Mammal === Parse.User && Mammal === Animal
var Mammal = Animal.extend({},{})

// Adds even MORE instance and static properties.
// You get the gist by now
var Cat = Mammal.extend({},{})
```
