### ISSUE TITLE
How could I enable cross origin in Parse Javascript SDK?

### ISSUE THREAD

**Issue by tomtomtong** [ParsePlatform/Parse-SDK-JS#288]
Hello. 
I would like to load video from Parse server in the front end html hosted in AWS. But there is security error when I run the page in iPhone Safari browser. I have checked it is about enable cross-origin resource sharing issue.  

How could I enable cross origin in Parse Javascript SDK? Thx

**Comment by andrewimm** [comment]
The Parse SDK does not control the headers that are served from your file storage location. If you are using the standard Parse Server database-based file storage setup, file an issue with ParsePlatform/Parse-Server. If you are using your own Amazon S3 bucket to store your files, the issue is in the configuration of your bucket.

Closing, since this does not involve the SDK.
