### ISSUE TITLE
Can we use serverURL with parse/node?

### ISSUE THREAD

**Issue by ndnguru** [ParsePlatform/Parse-SDK-JS#290]
I am trying to migrate my application using a self hosted parse-server setup.  I have some test scripts that I run in NodeJS using the parse/node module.  However when I specify a server URL, I get an error trying to connect to the parse server.

does the parse/node module support serverURL?

I am trying this:
```

Parse.initialize('API KEY WOULD GO HERE');
var serverURL = 'https://some.server.url/parse';
Parse.serverURL = serverURL;
```

and I get this error:
```
ParseError {
  code: 100,
  message: 'XMLHttpRequest failed: "Unable to connect to the Parse API"' }
```

**Comment by andrewimm** [comment]
It's supported. That's how all of the integration tests run, so I can guarantee that hasn't broken.

I'd make sure that your server running your node app can actually see your parse server, and that there are no networking complications, but I doubt there's an SDK bug here.

**Comment by ndnguru** [comment]
@andrewimm Thanks, that's what I figured also.  I have a web application running, which can see the parse server and the browser/client can access the parse server at the same URI, so based on that I do believe it is reachable.  I will dig in some more to see what else might be going on.

**Comment by andrewimm** [comment]
Well, good luck digging into this. I'd suggest trying to build a simple node script and seeing if it can make requests to your server using the `https` module. There might be some crazy permissions mismatch going on.

**Comment by ndnguru** [comment]
here is what I discovered... if I set the serverURL to `http` instead of `https`, I can connect the the remote parse-server.  Why?  In the browser, I point to `https` and it works fine. 

The web service is deployed on AWS, sitting behind a load balancer.  The interesting thing is that in the parse-server instance on the server, I use `http://localhost/parse` as the serverURL.  The load balancer handles `https` termination I guess, and passes the traffic over `http` internally? Atleast that is what I think is going on... but again, when I point to `https` from the browser, all good.

Any ideas here?

You mentioned making requests to the server using the `https` **module**... what did you mean by that?  is there a specific module I need to use to enable a TLS session using parse/node?

**Comment by andrewimm** [comment]
Nah, I just meant writing a simple node program that makes an http requests to your server, and sees if it can get _any_ response. I was referring to node's builtin `https` module, there's no configuration necessary on the `parse/node` side.

In most AWS setups with ELB, the ELB is the termination point for SSL (for speed reasons). Anything behind the load-balancer should be using http in its path, to connect to port 80, versus https, which will point to port 443. If it were going back out to the internet before reconnecting (for instance, to get the benefit of the load balancer), you'd still need the https protocol in there.

I want to keep Github issues focused on SDK bugs and improvements, so I'll be closing out this task, since I'm convinced it's tied to your infrastructure and topology.
