### ISSUE TITLE
parse-latest.js served on the CDN via HTTPS is serving a non-minified version of the code

### ISSUE THREAD

**Issue by cherukumilli** [ParsePlatform/Parse-SDK-JS#293]
To recreate the problem please do the following:

1. Open `https://www.parsecdn.com/js/parse-latest.js` in your browser window
2. Open `http://www.parsecdn.com/js/parse-latest.js` in an other browser window

You will see that the HTTPS version is non-minified and the HTTP version is minified.

Please let me know if I need to open this issue in a different place.

**Comment by andrewimm** [comment]
`parse-latest.js` is supposed to be non-minified. If you want minified, use `parse-latest.min.js`

`parsecdn.com` isn't currently supported, since the hosted service is going away, and few people actually use the SDK in that form. From the statistics I have, it looks like most people host their own or use the `npm` package to build a single package. If people want a hosted CDN, I'll look into using CDNJS or something similar.

**Comment by andrewimm** [comment]
I will update README.md to reflect the fact that the cdn is not maintained. I'll also try to update the backlog of pre-built distributions available on the releases page of this GitHub repo.

**Comment by cherukumilli** [comment]
@andrewimm Thank you for the clarification.

**Comment by reubenbrown** [comment]
Is there a timeline for when that latest versions might be put on CDNJS or a similar service?

**Comment by andrewimm** [comment]
I just found out about npmcdn, which is an awesome service because it doesn't require any extra effort to publish there.

You can pull in the SDK from there with URLs like https://npmcdn.com/parse@1.8.5/dist/parse-latest.js or https://npmcdn.com/parse@1.8.5/dist/parse-latest.min.js

Since it's a little awkward to call it "latest" at each version, I'll rename it to parse.js and parse.min.js from version 1.9.0 onwards. I'll update the README to contain this information when I do.

**Comment by reubenbrown** [comment]
@andrewimm Thanks appreciate it!
