### ISSUE TITLE
CLP setting for builtin classes like Session, User

### ISSUE THREAD

**Issue by gkrcode** [ParsePlatform/Parse-SDK-JS#296]
Default CLP settings for Session and User classes in parse-dashboard allows all (get, find, create, update, delete, add field) operations. My code does not directly access class like Session. It all done by Parse SDK. I am not sure what is the correct CLP setting for these classes. Should I leave as it is so Parse SDK wont break ? Confused.

**Comment by andrewimm** [comment]
Sessions and Users are not restricted by CLPs -- they are limited on a per-row basis by ACLs, so that only a user can write its own fields, and only a given session can see other sessions tied to the same user.

This means that by default, Sessions are not query-able at all, and Users are not write-able. However, the default CLP allows users to be queried through get / find requests (think, being able to see all Twitter users info by default). If you want to disable this functionality, you should restrict your User table CLP.
