### ISSUE TITLE
Query.skip limit

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/Parse-SDK-JS#298]
Is there any limit set for skip ? I thought there is something like 10000
What if i try to skip 20k, what happens ?

**Comment by andrewimm** [comment]
From the docs at https://parse.com/docs/js/guide#performance-limits-and-other-considerations

"The maximum value accepted by skip is 10,000. If you need to get more objects, we recommend sorting the results and then using a constraint on the sort column to filter out the first 10,000 results. You will then be able to continue paging through results starting from a skip value of 0. For example, you can sort your results by createdAt ASC and then filter out any objects older than the createdAt value of the 10,000th object when starting again from 0."

**Comment by benishak** [comment]
I was able to skip more than 10k but it just got slower

**Comment by benishak** [comment]
I think this limitation only exists on parse.com ?

**Comment by andrewimm** [comment]
Are you using parse-server, or the hosted service on Parse.com? If you're using parse-server, your skip limit is determined by the configuration of your underlying database.

In general, skipping is a very slow database operation, and should be avoided where possible. To skip, your query needs to retrieve all of the rows you're skipping into memory, only to throw them away later. That's why using a comparable index is much more scalable.

**Comment by andrewimm** [comment]
Regardless, this is related to the server and not the SDK, which is why I have closed this issue. Issues on this repo are for things related directly to the client SDK code.
