### ISSUE TITLE
Multiple users from node.js, any plans?

### ISSUE THREAD

**Issue by D219** [ParsePlatform/Parse-SDK-JS#299]
Following [this SO question](http://stackoverflow.com/questions/37963234/parse-server-node-js-sdk-alternative-to-parse-user-become/37963513?), it seems there is no way to have multiple Parse.User in node.js.

Instead, we have the choice between praying and enbling Parse.User.current, then switching users with Parse.User.become, or giving the server the masterKey, and rebuilding the ACL by hands.

Is there any supported way for a node.js server to make request to Parse on behalf of a User, or any plans to ad support for it?

**Comment by andrewimm** [comment]
This is definitely supported, sorry it's not clear from the documentation.

In node environments, it's best to keep the current user disabled. Instead, every single call to the server, such as `query.find()`, `object.save()`, etc. supports passing multiple options as the final parameter. One of the supported options is `sessionToken`, which ensures that the request is made on behalf of the user associated with that token.

Here's a quick example:
```
// fetch items visible to the user associate with `token`
fetchItems(token) {
  new Parse.Query('Item')
    .find({ sessionToken: token })
    .then((results) => {
      // do something with the items
    });
}
```

**Comment by D219** [comment]
@andrewimm : As a last question before this issue can be closed: when passing a session token to `Object.save()`, does it set the ACL too? Or do I have to take care of this?

**Comment by andrewimm** [comment]
I'm not 100% sure what you mean by set the ACL, but if you're talking about creating a new object and making it belong to that user, then the answer is: no, ACLs need to be explicitly set. This doesn't change any other object behavior.

Under the hood, when the SDK talks to parse.com (or your parse-server instance), it looks at the current user and – if it exists – injects its session token into the headers of that request. This option gives you direct, one-time access to that same header, so that you can be explicit about which user you make a request on the behalf of.

Just like being logged in, this will affect rows that have ACLs, as well as classes that have Pointer-level CLPs.

**Comment by D219** [comment]
Thats what I wanted to know, thanks a lot for your help :)
