### ISSUE TITLE
beforeSave issues with dirtyKeys

### ISSUE THREAD

**Issue by Silkjaer** [ParsePlatform/Parse-SDK-JS#31]
I am running my CloudCode on a node.js server, using webhooks as described in a recent blog post on parse.com, and using CloudCode-Express.

Everything seems to run smooth, however in my beforeSave triggers I need to check if certain keys are dirty and they never are?

```
Parse.Cloud.beforeSave("CLASSNAME", function(request, response) {
    console.log(request.object.dirtyKeys()); // always outputs an empty array to the console
    if(request.object.dirty("key") && request.object.get("key")) { // value is a boolean
        // never executes
    }
});
```

Is this a bug, or am I doing something wrong? Running the same triggers on CloudCode on Parse.com (non-self-hosted), works as expected.

**Comment by stanleyw** [comment]
Currently this is not supported by webhooks.  The dirty keys are not passed to webhooks by the Parse backend according to the current spec (https://www.parse.com/docs/js/guide#cloud-code-advanced-beforesave-webhooks), so the JS SDK can't populate this field in Node.js.

However, we are always looking to improve the platform.  Could you talk more about your use case and why you need this information?

**Comment by Silkjaer** [comment]
Thanks for the reference, I was looking all over for this.

I am relying on some node.js plugins that I can't implement in CloudCode, so I made a quick decision to move all code to Heroku (without noticing the dirtyKeys limitation). I want to avoid maintaining server side logic in too many places :)

I am often using the change of a key's value as a trigger to another action, e.g. updating a related object. I do not want to trigger these actions on every save, but only if a specific key's value is changed.

I am also validating keys if they are dirty, e.g. to set a default value or verify it is not undefined.

Would it be possible to somehow trigger a warning log message if unsupported functions are used? 

Thanks!

**Comment by zicker** [comment]
To piggyback off of this issues:
In version 1.5.0 of the SDK it was possible to detect if a client changed the ACL of the Parse.User object with the following logic:
`Parse.Cloud.beforeSave(Parse.User, function(request, response) {
    if(!request.master && request.object.dirty('ACL')) {
        //ACL of user object modified
    }
});`
It appears that this is no longer the case. Is this intentional or a bug?

**Comment by andrewimm** [comment]
@zicker are you referring to code running in Node.js, or on Parse Cloud Code?
This issue is regarding code running on a privately hosted Node server, using our Webhooks service.

That said, the behavior you mention should still be supported in 1.6.4. We have tests that suggest it works in the current version (1.6.4)

**Comment by zicker** [comment]
@andrewimm Running it on Parse Cloud Code. I probably should have created a new issue for this... sorry about that!

**Comment by stanleyw** [comment]
@Silkjaer please see https://github.com/ParsePlatform/parse-cloud-express/issues/4
