### ISSUE TITLE
Are there any compatibility issues with Parse.com

### ISSUE THREAD

**Issue by simonaberry** [ParsePlatform/Parse-SDK-JS#310]
Is it safe to use e.g. v1.8.5 in your client to talk to a legacy Parse.com server ? we are in the process of migrating, but want to know if its safe to update all clients to the latest JS SDK version before the server has migrated fully...

**Comment by andrewimm** [comment]
It should be completely safe. The SDKs up to and including 1.9.0 are still compatible with the legacy service, as long as you avoid using new features like `LiveQueries`.

Just be aware of any behavioral changes that have taken place since 1.6.14 (or whatever you're migrating from). The biggest is the change to the way Promises handle errors: we've changed the default behavior to support the newer Promises/A+ spec, which means errors generate rejected Promises, rather than bubbling up and creating a stack trace. If this becomes a problem, you can always go back to the way things were by calling `Parse.Promise.disableAPlusCompliant()` when you initialize the SDK.

**Comment by simonaberry** [comment]
Thank you for the great feedback.

I have noticed a slight difference (I think). If you perform a query, then modify the results, but **don't**  save the changes back to the server... then if you repeat the same query you will get the modified results (rather than a fresh set of objects from the server).

I would guess that this is resulting from the new sdk doing some sort of local caching ???

**Comment by andrewimm** [comment]
It sounds like you're describing changes that took place in 1.6.0. Which version of the SDK were you using previously?

**Comment by simonaberry** [comment]
you are right.. I was using 1.3.1....

p.s.not sure if I should close this issue or not (to help others who might have the same question)

**Comment by andrewimm** [comment]
Yep, 1.3.1 is very old. Many things have changed in that time.

What you're describing is the introduction of Single-Instance mode, which makes it easier to develop client-side applications that keep their UIs in sync. If it's causing you trouble, you can disable it with `Parse.Object.disableSingleInstance()`.

Since the issue has been "resolved," I'd like to close it out. Closed tasks are still searchable on GitHub and Google, so they're still easily found by others answering the same question.
