### ISSUE TITLE
Parse.File sends incorrect Content-Type to API

### ISSUE THREAD

**Issue by samuelantonioli** [ParsePlatform/Parse-SDK-JS#311]
Hi,

first the issue:
a) I want to upload a PDF file using Parse.File:
```
// assume you have a File-Object in variable "file" with a PDF file
var file_obj  = new Parse.File('test.pdf', file, 'application/pdf');
```

b) Everything is fine while saving, S3 stores the file
c) But then I get "Failed to load PDF document" from S3.

Reason: I get this error message because S3 sends me `Content-Type: text/plain` for my PDF file

- - -

So back to step b) &mdash; I can see the following happening:
Parse sends a `POST` request to the API to save the file with the following headers:
```
X-Parse-Application-ID: ...
X-Parse-JavaScript-Key: ...
Content-Type: text/plain
```

Q: Why is it sending `"text/plain"`, although I've told Parse.File that I want to upload something with mime type `"application/pdf"`?
A: Someone wanted to avoid pre-flight requests and hard-coded the `Content-Type: text/plain` in the REST Controller (see [this](https://github.com/ParsePlatform/Parse-SDK-JS/blob/9a521e948a966188361af9d9bf544e3da47f01cc/src/RESTController.js#L128)).

- - -

**Solution 1**

After deleting this line: `headers['Content-Type'] = 'text/plain'; // Avoid pre-flight`
there is no problem with the Content-Type and I get my PDF file with the correct Content-Type.

Is there any reason to hard-code the Content-Type there? The only downside is that browsers will send `OPTIONS` requests to make sure that they can do CORS.

**Solution 2**

If there are other disadvantages I didn't consider in Solution 1, is it safe to use something like this? i.e.

```
// replacing line #128: https://github.com/ParsePlatform/Parse-SDK-JS/blob/9a521e948a966188361af9d9bf544e3da47f01cc/src/RESTController.js#L128
if (!(data instanceof File)) {
    headers['Content-Type'] = 'text/plain'; // Avoid pre-flight
}
```

**Solution 3**

All those suggestions above would ignore the mime type that gets passed as a third argument for Parse.File e.g. if `file` is a File-Object with `file.type == 'application/pdf'`, then `new Parse.File('filename.png', file, 'image/png')` would still send Content-Type `"application/pdf"`. It would be interesting to hear if there are some real world use cases that need to set another mime type.  

If there are use cases for this, `saveFile` (see [this](https://github.com/ParsePlatform/Parse-SDK-JS/blob/9a521e948a966188361af9d9bf544e3da47f01cc/src/ParseFile.js#L235)) should be changed and combined with Solution 2. This would result in the following change in `saveFile`:

    var headers = {
      'X-Parse-Application-ID': CoreManager.get('APPLICATION_ID'),
      'X-Parse-JavaScript-Key': CoreManager.get('JAVASCRIPT_KEY'),
      'Content-Type': source.type || (source.file? source.file.type : null)
    };

This would have the desired behaviour:
- `Parse.File('test.pdf', file, 'image/png')` will send `Content-Type: image/png` (Third argument overrides `file` mime type)
- `Parse.File('test.pdf', file)` will send e.g. `Content-Type: application/pdf` if `file` is a PDF file (or `file.type` so for a png file it would send `"image/png"`)

- - -

I would like to push **Solution 3** into the repository, do you agree?  
Please comment on this issue or - if you experienced similar problems - say if Solution 3 helped you.

**Comment by andrewimm** [comment]
So I'll provide some background on this code. I think this is an oversight on my part, but it should still be working as intended.

When file uploads were first introduced, each client SDK actually shipped with a large mapping of file extensions -> mime types. If a file was uploaded without the user specifying a specific type, we used this to estimate the content type. Sometime in 2015, before the open sourcing of the SDKs, I changed the backend behavior of Parse.com to attempt this content-type estimation instead. I'm guessing that `parse-server` doesn't take this same approach, at least not when a `File` is directly uploaded.

Furthermore, it used to be that you couldn't upload `File`s directly, and the SDK would convert it to a JSON payload including a Base64 string of file contents. I figured that the typical use case for users involved actual File objects, and decided that POSTing these objects directly to the server would streamline the process. This functionality was enabled as part of the major changes in the release of 1.6.0. This is probably where the mismatch was introduced: users with the Base64 upload method continue to pass a JSON payload to the server that contains the custom mimetype, when provided, but users who upload Files directly depend on the server interpreting the type. We didn't notice this issue when 1.6.0 was launched, because we were only supporting one backend at the time (Parse.com hosted) which I had explicitly configured to interpret the content type off of the filename. I'm sorry this didn't come to my attention until now.

I absolutely support your third solution, with the slight requirement that we also need a check in RESTController to see if the `content-type` header wasn't already set by the caller. Uploading `File` objects is the only action that calls directly into the underlying `ajax` method, so we already expect it to have some special handling that is unrelated to the rest of the SDK's calls. I'll also attempt to flesh out some of the tests around file uploads, since that could have caught this before today.

**Comment by samuelantonioli** [comment]
Thanks for your detailed explanation and analysis of the problem. I must admit that `Parse.File` and its easy usage brought me to Parse after the code was released.

I'm curious whether the Parse SDK still tries to guess the mime type, because I'm not convinced that client-side mime-type detection can be trusted anyways. Hopefully `parse-server` uses reliable mime type detection techniques and not extension-based detection. &mdash; I think the relevant issue was [#1900](https://github.com/ParsePlatform/parse-server/issues/1900) but it looked like the server blindly trusts the client.

So I think the following changes would work, but I would like to have some feedback regarding case-sensitivity: Are the header props already normalized or do you expect different capitalizations e.g. is `"Content-type"` valid?
```javascript
// In RESTController.js
// naive approach (what happens if "content-type" or "Content-type" is given?)
headers = headers || {};
if (typeof(headers['Content-Type']) !== 'string') {
    headers['Content-Type'] = 'text/plain'; // Avoid pre-flight
}

// In ParseFile.js (saveFile)
var headers = {
    'X-Parse-Application-ID': _CoreManager2['default'].get('APPLICATION_ID'),
    'X-Parse-JavaScript-Key': _CoreManager2['default'].get('JAVASCRIPT_KEY'),
    'Content-Type': source.type || (source.file? source.file.type : null)
};
```

If `saveFile` is the only method that calls `ajax` directly it may be sufficient to check `"Content-Type"`.

- - -

**off-topic**
Unfortunately it looks like `parse-server` has a behaviour regarding file uploads that could be harmful in most cases: I've uploaded a html file containing Javascript code (which a malicious party could easily do using the app_id and the javascript_id) and nothing prevents it from doing a XSS attack - on a self-hosted system some people may end up with the file storage, API and the web app on the same domain if they don't use e.g. the S3 adapter (i.e. GridStore), so this means that a attacker could send a file to `parse-server` and has a persistent XSS attack on the server.
I don't think that it is `parse-server`'s fault, but I do think that most people who use systems like Parse don't know/care about the relevance of subdomains to divide important parts and even then `"text/html"` and other types of files that can control the browser should probably be saved as `"text/plain"` or not at all by default to minimize the risk (e.g. using whitelisting). I guess most of the users of Parse are storing images or other media, otherwise this issue I brought up had been found much earlier.

Can you give me a direction where such discussions can be found? I don't want to pollute this issue.

**Comment by andrewimm** [comment]
Header types aren't normalized, but as I said FileController is the only part of the SDK that directly touches `.ajax()`. Let's move forward with the `'Content-Type'` string, and be confident that we're using the same string in both places.

> I don't want to pollute this issue.

You are an open source maintainer's best friend :)

I don't believe there's any active discussion on the `parse-server` front. I dug deep into this issue long ago for the Parse.com servers, and decided that extension-based checks are more than adequate. It'd be unweildy to try and check every magic number / formatting combo to verify the type of a file, and developers have the ability to override if that system isn't working. Ideally you should know the types of files you're uploading, and be able to use the override in this constructor. In the Parse.com Golang implementation, I was able to call into the underlying system's mimetype reference table, which I personally like more than some of the hard-coded solutions that exist for node. I'm not super familiar with that part of the codebase, but I'll see if I have the time to put together a `parse-server` PR.

**Comment by samuelantonioli** [comment]
Ok, PR sent. I don't have the time to write a test case covering this now, but I hope somebody can think of a good way to test this change.

Thank you for explaining the decision! I would be glad if you could notify me if there is any progress in the `parse-server` discussion or in your PR.

Hopefully this issue can be closed soon - thanks for your fast response time.
