### ISSUE TITLE
How to create a new Parse Object from a regular JSON object?

### ISSUE THREAD

**Issue by srameshr** [ParsePlatform/Parse-SDK-JS#315]
```
  var obj = {
   createdAt: Fri Jul 15 2016 22:27:00 GMT+0530 (IST),
   updatedAt: Sat Jul 16 2016 00:53:11 GMT+0530 (IST),
   objectId: "KZdfedg3yd",
   name: "John"
  };
```

How do I convert this into a ```Parse Object``` so that I get methods like ```get```, ```set``` on this object using the Parse JS SDK?

```
obj.get("name") // "John"

```

I can manually extend this to achieve this, but is there any built in method in the JS SDK that takes an objet and adds getters and setters ?

**Comment by srameshr** [comment]
@andrewimm  Any updates on this?

**Comment by cherukumilli** [comment]
@srameshr 
Did you get a chance to check the following: https://parse.com/docs/js/api/classes/Parse.Object.html#methods_fromJSON ?

I think you should be able to do something like this:
```
    var MyClass = Parse.Object.extend("ClassName");
    var object = new MyClass();
    object.fromJSON(myJSON)
```

Please let me know if this doesn't work.

**Comment by srameshr** [comment]
@cherukumilli 

Thanks for the response. But it does not work. 
```fromJSON```` is not available as a method on ```object```

Check it out in the console. 

Here is the link to JSBin showing the issue:
[https://jsbin.com/yaheloreno/edit?html,js,output](url)

**Comment by srameshr** [comment]
```
 var object = new Parse.Object("ClassName");
```

```add``` method is available, where it takes a JSON object. But accessing multilevel nested obj is not working.

```
object.add({
  a: {
    b:1
  },
  c:2
});

object.get('a') // b:1
object.get('a').get('b'); // This does not work.
object.get('c'); // 2, This works.

**Comment by andrewimm** [comment]
@srameshr @cherukumilli `fromJSON()` is a static class method, so it is used as `var obj = Parse.Object.fromJSON( JSON_PAYLOAD )`

`.add()` does not do what you assume it does. It is for atomically appending objects to the end of an array.

**Comment by srameshr** [comment]
@andrewimm Why did you close? This still does not solve the problem?
```
var obj = {
   createdAt: Fri Jul 15 2016 22:27:00 GMT+0530 (IST),
   updatedAt: Sat Jul 16 2016 00:53:11 GMT+0530 (IST),
   objectId: "KZdfedg3yd",
   name: "John"
   className: "Foobar",
  a: {
    b: 1
   }
  };

var temp = Parse.Object.fromJSON(obj);
console.log(temp.get('a').get('b')); // This does not work
```

However, if I return some data from parse cloud ```temp.get('a').get('b')``` will give out the proper response.

**Comment by andrewimm** [comment]
@srameshr I closed the issue because there is no bug with the SDK here. I'm happy to help with questions, but issues on this GitHub Repo are reserved for problems with the underlying code itself.

For a Parse Object, `get` and `set` are used to interact with the fields that exist directly on the object. In your example above, `Foobar` has a field called `a` which is a standard JS object. Since it is not a Parse Object, it does not have a `.get()` method. The following two scenarios are essentially equivalent:

```js
var b = temp.get('a').b;

var b = obj.a.b;
```

**Comment by srameshr** [comment]
@andrewimm I get that. But in my codebase, I have used ```obj.get('a').get('b')```.
Now I am refactoring my cloud code and returning an object from cloud, like 
```
respose.succes({
  // Data
});

```
So, client code is just throwing now.

**Comment by andrewimm** [comment]
I'll admit, I'm very confused about your use case.
In this scenario, is `a` supposed to return a Parse Object? That's the only way I can understand how `.get('a'`).get('b')` would work.

Can you provide some more information on exactly what you're trying to achieve? What's involved in this refactor? What worked before, what isn't working now?

**Comment by srameshr** [comment]
Sure! Bare with me.

<b>From my cloud code</b>
```
let Foobar = Parse.Object.extend("Foobar");
let query = new Parse.Query(Foobar);
query.find().then((data) => {
  
  response.success({
    // Nested structure here, since I want very few fields from the data object.
   createdAt: Fri Jul 15 2016 22:27:00 GMT+0530 (IST),
   updatedAt: Sat Jul 16 2016 00:53:11 GMT+0530 (IST),
   objectId: data.id,
   name: "John"
   className: data.get("className"),
  a: {
    b: 1
   }
    a: {
      b: data.get('someKey')
    }
  })
}, null);

```

<b>Client code </b>
```
Parse.Cloud.run('Foobar').then((data) => {
  console.log(data.get('a').get('b')) // Error
});
```

**Comment by andrewimm** [comment]
Okay, here's the issue: you're doing custom encoding, and you can't expect that inner object to be re-inflated into a Parse Object.

`.get('a').get('b')` works in your cloud code because `'a'` points to another Parse Object. But then you construct a new object, where `'a'` points to a Plain Old JavaScript Object, with a single key `'b'`. When that payload gets back to your client, `'a'` still points to that same POJO, not a `Parse.Object`, so it does not have any `Parse.Object` methods like `get()`

**Comment by srameshr** [comment]
I cant use ```select``` because, that is coming from an ```query.include()```. It just includes the whole row without allowing me to select specific columns. 

Tried providing ```className``` and ```objectId``` fields on ```'a'```. Still does not work.

**Comment by andrewimm** [comment]
Sorry, you'll also need a `__type` field that points to the string `'Object'`

This is why we discourage people from trying to attempt to do their own encoding. The SDK and the Server have certain expectations, and there's usually a better way to achieve what you're trying to do.

**Comment by srameshr** [comment]
Tried that. Still the same. Does not work. In the end, I ended up updated my client code. Thank god, it was an angular directive calling a service that constructed the object. 

BTW, what is the better way? Any general advice on how I might want to overcome this problem of selecting few fields from ```query.include``` ?

**Comment by andrewimm** [comment]
I don't know your exact scenario, so I won't attempt to provide specific alternatives. Ultimately it does depend on what you're trying to accomplish.

This works for me: https://jsbin.com/vecumapoto/edit?html,js,output

You need to provide the extra __type fields because Cloud Code doesn't know that you're trying to encode an actual Parse Object. It needs a way to differentiate between an arbitrarily-constructed object that might contain a 'className' field, and a true Parse Object. If you had called `response.success()` with the original Parse Object as the argument, there would have been no issue.

**Comment by linpf870208** [comment]
@andrewimm  
var obj = Parse._decode(null, {
    __type: 'Object',
    // objectId: 'myid',
    name: 'John',
    className: 'Item',
    a: {
      __type: 'Object',
      className: 'Inner',
      b: 'somekey'
    }
   });

  obj.save(null, {useMasterKey: true});


 i need to create a parse object from json  string ,and i do this follow you advice.but when i save this object , it can't work as expected, why?
