### ISSUE TITLE
Parse Not Recognizing Objects

### ISSUE THREAD

**Issue by caseygauss1** [ParsePlatform/Parse-SDK-JS#325]
Using the Javascript SDK it seems as though Parse is having a hard time communicating with the database. Simple code I've been using for the past few moths has all the sudden stopped working.

Couple of Examples:
     1) Querying a user account. Only intermittently when making a query, I get a 400 errors saying bad request. 
      2) Updating an object. When trying to update an object, I get an error saying that the object does not exist, but I can look up the object with the exact same id from within the data browser.

**Comment by andrewimm** [comment]
Sounds like there's something wrong with your server setup, not the SDK. What version of Parse Server are you running?

**Comment by caseygauss1** [comment]
We've not yet migrated away from Parse hosting.

**Comment by andrewimm** [comment]
In that case, the bad request errors might be due to problems with  the hosted Parse system. As for the object that appears in the data browser, but cannot be updated by your code, I would make sure that you actually have access to the object. If it's protected by a CLP, an ACL, or something along those lines, it would appear in the data browser but would appear to not exist to any improperly-authenticated code.

Since this is not an issue with the JS SDK, I'm closing this out.
