### ISSUE TITLE
Incomplete Parse Object Returned

### ISSUE THREAD

**Issue by parkej60** [ParsePlatform/Parse-SDK-JS#339]
I'm making a pretty straight forward Parse Query from the client side, a BackboneJS Application.

```
var Restaurant = Parse.Object.extend("Restaurant");
var query = new Parse.Query(Restaurant);
query.limit(20);
query.descending('rating');
query.find().then(function(restaurants){
           view.$el.html(view.template({restaurants:restaurants}));
},function(error){
            console.error("Error: " + error.code + " " + error.message);
});
```

The query returns a list of objects in the following format:
```
{
_objCount: 0
className: "Restaurant"
id: "NtfeOn3dFH"
}
```

I've read all the threads about .toJSON, but this isn't Cloud Code so I'm not sure what exactly is going on. 

ParseServer:2.2.18
Javascript-SDK:1.9.1

**Comment by andrewimm** [comment]
The attributes are probably there and available via `.get()` -- they just don't show up when you call console.log. This is due to the way they're calculated, and to reduce noise when printing lots of objects. Rather than `console.log(obj)`, you can do `console.log(obj.attributes)` and you'll get the set of attributes.

**Comment by parkej60** [comment]
That was it! Thanks!!!
