### ISSUE TITLE
  Duplicate module name: parse

### ISSUE THREAD

**Issue by etamity** [ParsePlatform/Parse-SDK-JS#352]
**I installed parse server and parse client sdk from npm, and got the naming collision error. Any idea?**

============
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: parse
  Paths: /Users/etamity/Documents/etamity/dev/IOS/react/ultimateApp/node_modules/parse/package.json collides with /Users/etamity/Documents/etamity/dev/IOS/react/ultimateApp/node_modules/parse-server/node_modules/parse/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: parse
  Paths: /Users/etamity/Documents/etamity/dev/IOS/react/ultimateApp/node_modules/parse/package.json collides with /Users/etamity/Documents/etamity/dev/IOS/react/ultimateApp/node_modules/parse-server/node_modules/parse/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/etamity/Documents/etamity/dev/IOS/react/ultimateApp/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:155:13)
    at p.getName.then.name (/Users/etamity/Documents/etamity/dev/IOS/react/ultimateApp/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:130:31)
    at process._tickCallback (internal/process/next_tick.js:103:7)
~

**Comment by andrewimm** [comment]
Which version of npm? npm 3 should resolves these types of errors.

Also, why have you installed parse-server as a dependency of a React Native app? That's possibly the bigger issue. The React Native packager is getting confused because parse-server and all of its dependencies are in the same `node_modules` folder as your client's dependencies. From a structural perspective, I'd recommend putting your server in a separate directory from your react-native project, each with its own `package.json` and `node_modules`.

Either of the suggestions above should fix this. It's an issue with setup, not the Parse SDK.
