### ISSUE TITLE
Calling to Cloud Code method returns no response if response has no data

### ISSUE THREAD

**Issue by hydex86** [ParsePlatform/Parse-SDK-JS#357]
I'm calling to a custom parse server (v.2.2.22) from JS SDK (v.1.9.2) this way:

```
Parse.Cloud.run("getOrders",` options, {
    success: function(results) {
        res.render('orders', { orders: JSON.parse(JSON.stringify(results)) }); 
    },  
    error: function (error) {
        res.redirect('/');
    },  
});
```

Everything is ok if getOrders cloud code method response has objects. But if getOrders response has no orders, success and error functions are not called. 

I checked in server logs and I got a 200 status code response, so I think the problem is on JS SDK.

**Comment by andrewimm** [comment]
What does your cloud code look like? Parse Server should always be sending back a response, so it should always be triggering your callbacks.

Also, check if using the Promise returned by the call to `run()` works. It should be automatically triggering your callbacks, but it will help determine where the issue is.

```
Parse.Cloud.run('getOrders', options).then(function(results) {
  res.render('orders', {orders: JSON.parse(JSON.stringify(results))});
}, function(error) {
  res.redirect('/');
});

**Comment by hydex86** [comment]
I checked it again and it was my fault. My cloud code response was a string when there was no data, I just fixed just by responding 
    
    res.send([]);
