### ISSUE TITLE
Documentation for Parse.Object.saveAll does not indicate return of Parse.Promise

### ISSUE THREAD

**Issue by richardgroves** [ParsePlatform/Parse-SDK-JS#365]
The documentation for Parse.Object.saveAll:

https://parseplatform.github.io/Parse-SDK-JS/api/classes/Parse.Object.html#methods_saveAll

gives no indication that the method returns a Parse.Promise object, whereas in reality it appears that it does: https://github.com/ParsePlatform/Parse-SDK-JS/search?utf8=%E2%9C%93&q=saveAll

**Comment by richardgroves** [comment]
Sorry - my misunderstanding, it is just the way it is used in the tests that make it look like you can chain a promise from it.

So would it be possible for saveAll to return a promise? It is one of very few (Query.each) where I have to mix in the backbone style call backs.

**Comment by andrewimm** [comment]
Not sure I understand. `saveAll` does return a Promise that resolves if and when all objects have been saved. It is oddly missing from the documentation, but that can be fixed by a quick PR.

FWIW, `Query.each` does not require you to mix in backbone style callbacks. It allows you to attach a per-item callback (not a success/error pair), due to the inability to cleanly attach Promises to that type of request. And when its done, it does return a Promise for the entire process.

**Comment by richardgroves** [comment]
Apologies for the confusion Javascript is definitely not my primary language and I was getting confused by various types of callback, and a typo in my example code lead to the saveAll promise not working.

Glad to have it confirmed that the saveAll does return a promise, and I've managed to fix my code to use it. Hopefully someone can do a PR for the documentation - given my lack of understanding I wont risk it myself.

And thanks for the clarification on Query.each - re-reading the documentation with your comment has cleared it up for me.
