### ISSUE TITLE
Why return pointer when encoding dirty object

### ISSUE THREAD

**Issue by hector-romero** [ParsePlatform/Parse-SDK-JS#369]
May I ask the point of returning a Pointer instead of the _fullJSON object when it is dirty in encode.js->encode?

https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/encode.js#L30

I'm queriying a set of objects with an include that is modified before returning the result:

    mainObject.get('subobject').set('attr','modification');
    response.success(mainObject._toFullJSON());

when doing that, the included object is sent to the client as a pointer, but if it is not modified then it is returned as a full object.
This seems to be an inconsistent behavior, since when I run `mainObject._toFullJSON()` it returns the specified mainObject as a whole, including the modified attributes.

Thanks.

**Comment by andrewimm** [comment]
This has existed since cloud code was originally launched, and there are good API and data-consistency reasons for it. The core issue boils down to the simple fact that the SDK doesn't expect to receive dirty operations from the server. It is not set up to decode them. Enabling the server to send both the current value and the modified value would require significant changes to the wire format, and older clients might not be able to interpret it properly. Right now, operations are designed to be sent alone to the server -- the client doesn't need to send the original value as well, since it's applying the change directly to the DB. If we sent changes in the reverse direction, the client would still need to know the original value as well, so that it can:
 - estimate the values of atomically-updated fields
 - perform unset operations on dirty fields
 - stack multiple atomic operations before saving
All of these require us to extend the wire format, which just isn't feasible at this point.

There are also concerns about data consistency. They're a bit more abstract and opinionated, but chances are good that sending dirty objects from the server increases the chances for bugs and unintended behavior.

To do what you're attempting to achieve, I would send back an object containing your original ParseObject, as well as changes you want to apply on the client once it gets there. Something like:

```
response.success({
  object: mainObject,
  changes: {attr: 'modification'}
});
```

Also, you'll notice that `_toFullJSON` is prefixed with an underscore. This is a common JS pattern to indicate a private method. It is not intended to be called directly, since it's only used internally. By calling it here, you're interfering with the expectations of the server when encoding the object, and the expectations of the client when decoding it, and you risk passing invalid code to your client. You should be calling `response.success(mainObject)` if you wish to pass an object back.

**Comment by hector-romero** [comment]
I really don't buy at all what you're saying because:

- sending dirty objects from the server increases the chances for bugs and unintended behavior: You're protecting us, the developers from a 'problem' that is not there as I see it, I we made changes in backend that are not saved, we probably have a reason for it.

- the client (being client the frontend) shouldn't care if something is  a 'change' or how is the data saved in the server/db. We should be able to generate extra info in backend that is not really in the db (for example: because it depends of a setting seved in other place) but that is needed in frontend.

- I agree that _toFullJSON  is private, but it's (was) the only way to get the JSON representation of an object (including the 'className' and 'type' propertied needed in client side to regenerate it with the original class) and to avoid the error "can't send an unsaved object" and that workaround is working perfectly fine in the parse-cloud server (the one that will be removed next january) wich brings me to the question: 

 > This has existed since cloud code was originally launched

When you say 'originally launched' you're talking about the open source here in github, right?

**Comment by andrewimm** [comment]
I may have originally misunderstood exactly what you wanted to do between server and client, which is why some of my previous answers don't align with your expectations. I thought you were trying to ensure that the changed object, when received by the client, is still "dirty" and can be reset (eg, you were priming the set of changes on the object). Now, it sounds like you simply want to intercept the object and send back a different format to the client, as though that value came from the database, I can provide better feedback.

When I say originally launched, I'm talking about September 2012:
http://blog.parse.com/announcements/welcoming-cloud-code-to-the-parse-family/
When this SDK codebase was open sourced and rewritten from the ground up, we needed to maintain the same functionality as previous versions, and there's an explicit test for this case in the older codebase that expects the nested object to generate a pointer. Parse Objects are designed to be a client-friendly representation of the data that exists in a given row of your database. As such, they're intended to represent the true state of your database.

There is an additional reason, totally unrelated to cloud code, as to why this code exists: when you save a Parse Object, it saves all dirty children, and then saves the parent. If A points to B, and B has no ID, we need to save B first and obtain an ID before we can construct an association between A and B that we can save to the server. This means we take two network requests to complete the process. If B **does** have an ID, we can save everything together. We include the dirty changes for B and A in the same request. If one of those changes is the creation of a pointer to B, we can't encode B directly as a child of A, and so we send it over the wire as a Pointer. This allows us to combine both operations into a single network request.

Forking the behavior depending on whether you're running through cloud code or the client would be too risky, and I can come up with a few scenarios where it would introduce unexpected behavior on some clients, so we can't make a change here. The best workaround that I can come up with is to do exactly what you've done before, but make the change on the JSON representation of the object:

```
const json = mainObject._toFullJSON();
json.subobject.attr = 'modification'
response.success(json);
```

Hopefully that helps.

**Comment by hector-romero** [comment]
Oh great. Now it all makes more sense. Sorry, I probably could have explained myself better.
Thanks for following, still there's a small point, that is: the code was working before, by just doing _toFullJSON() all childrens were sent to the client completed even when they where dirty, now if they are dirty they become simple pointers, with no attributes. but this may also be related to the fact that we probably don't have the latest cloud code version running in parse.com (1.2.18).
Thanks for following this and for the clarification.
