### ISSUE TITLE
Latest published is not compatible with parse server ~2.2.24

### ISSUE THREAD

**Issue by maxMint** [ParsePlatform/Parse-SDK-JS#377]
After latest update of open-source parse server to:
    "parse": "~1.9.2",
    "parse-server": "~2.2.24"

JS SDK client is not working anymore, it looks like `application-id`, `javascript-key` and `session-token` must be send using headers (i.e. `X-Parse-Application-Id`), but latest published sdk uses json parameteres. 

Related issue https://github.com/ParsePlatform/parse-server-example/issues/298

Currently using patched version https://gist.github.com/maxMint/70b079de2a7047aea1e4c68c19b72ff9

**Comment by andrewimm** [comment]
The JS SDK needs to use the payload format – instead of headers – to maintain compatibility across a range of web browsers. If this is broken, it's a recent issue on the server side, but I trust them to have a reliable set of integration tests to avoid issues here, so it's probably an issue around setting up the SDK.

I just ran the full suite of JS SDK integration tests against 2.2.24, and it works for me.
