### ISSUE TITLE
Return Session Token from CloudCode

### ISSUE THREAD

**Issue by felix-dumit** [ParsePlatform/Parse-SDK-JS#61]
I don't know if this is the proper place, but this is the issue I'm having:

I want to implement my own authentication method (integrating with a 3rd party service), and for that I have Cloud Function that logs the user in and returns the session token, so that on the client I can call `become` and effectively log that user in.

Before I enabled revokable sessions this worked fine because I was able to get the user then call `user.getSessionToken()` and return it.
But after rovocable sessions were enabled the session tokens are always `undefined`. 
The only solution I was able to find is to manually re-login the user in CloudCode, but in order to do that I needed to know the user's password.
So the only was I was able to do it was by changing the user's password to a new random string every login so I could do it in CloudCode and return the session token?

I don't think it is a very good solution and I'm sure there has to be a better way.

Thanks!

**Comment by andrewimm** [comment]
The issue is that with revocable sessions, the relationship between User and Session is one-to-many. Therefore, fetching a User object can't return a specific session token, because there are many.

Today, if you want to do what you're describing, you have to do something hacky with passwords like you describe (I recommend setting it to the unique identifier you typically receive from oauth-type services). However, enabling developers to easily implement their own third-party auth is something we're actively working on! It'll let you use cloud functions to perform third-party auth from your devices.

**Comment by felix-dumit** [comment]
Thank you @andrewimm. I was previously creating a random password but the unique identifier is better since the password doesn't have to be changed. 
Still if the user wanted to be able to login using traditional email/password this would be a problem, so looking forward to the future improvements.

**Comment by tanmays** [comment]
I'm having a similar issue wherein I have  register and login methods defined in Cloud Code and accessing them on iOS/Android. 

After logging in/registering, upto Parse SDK v1.5.0 I was able to get the Session Token via `Parse.User.current()._sessionToken`

But ever since updating post 1.6.x the sessionToken is undefined. Is there any way to use cloud code functions and have login and register functions to work?

In my opinion after successful login/registration via the `.logIn` or `.signUp` the returned user object should itself include sessionToken, I'm not sure why this isn't by default.
