### ISSUE TITLE
PushId

### ISSUE THREAD

**Issue by alexblack** [ParsePlatform/Parse-SDK-JS#79]
Hi, I see its possible to lookup pushes in the dashboard by pushid, and see the delivery report.  How do I get the pushId so I can look one up?

Thanks,

Alex

**Comment by andrewimm** [comment]
At this point, you can only get the push ID from the dashboard. Due to the way pushes are created, we cannot provide IDs at creation time.

Also, please reserve GitHub issues for JS SDK bugs or features. Questions about using the Parse platform should be posted to one of our support platforms found at https://parse.com/help.

**Comment by alexblack** [comment]
"Also, please reserve GitHub issues for JS SDK bugs or features"

Isn't this a feature?  The feature would be that the SDK returns an ID for the push that it could be looked up with.  Any normal SDK would have a feature like this, wouldn't it?

**Comment by andrewimm** [comment]
Okay, it wasn't clear that you were asking for functionality. Typically, "how do I" questions are not tied to SDK features.

As noted, the API doesn't provide the id information at creation time, so there is no way the SDK can get that information.

**Comment by alexblack** [comment]
Features like this are generally expected, so when I couldn't find it I thought I'd ask first rather than assume.

So it sounds like you're saying this is someone else's problem, and you have no interest in getting this functionality added?

**Comment by alexblack** [comment]
If your stance is that this is someone else's problem, where can i file a feature request?

**Comment by andrewimm** [comment]
@alexblack I'm sorry if I made my position unclear. Speaking for the Parse platform, we're happy to accept feature requests for our API, and implement them if they are feasible. However, there is a significant difference between implementing a client side feature and one that affects our entire stack. API changes require deeper examination and design discussion, since they're essentially irrevocable.

With that said, I agree that this would be useful data to have when creating a push, and I'll discuss it with other team members to see how we can move forward here.

**Comment by alexblack** [comment]
Great to hear, thanks. It would be super useful, for those who send lots of pushes it would allow us to find the push in the dashboard to debug what went wrong if it didn't get received.
