### ISSUE TITLE
Cloud code: has no method '_isNullOrUndefined'

### ISSUE THREAD

**Issue by vikmeup** [ParsePlatform/Parse-SDK-JS#80]
Randomly in some requests to Cloud Code I'm getting this error. Does not tell me exactly where is happened.
```
[Error]: Uncaught TypeError: Object [object Object] has no method '_isNullOrUndefined' (Code: 141, Version: 1.9.1)
```
Requests sent by iOS SDK to Cloud Code Function. 

Thanks

**Comment by wangmengyan95** [comment]
Hi @vikmeup, in your case, could you provide the following info:
1. The cloud functions you call
2. The request the cloud function gets(you can just print it to console.)
Thx

**Comment by benjaminmcdonald** [comment]
I'm also getting this error.

has no method '_isNullOrUndefined'

No code line trace from cloud code either

**Comment by peterdotjs** [comment]
@benjaminmcdonald as stated earlier in the thread could you provide more information?

**Comment by domenukk** [comment]
I am getting this error, sporadically, in beforeSave.
It sometimes happens for one image when a user uploads 20 images. 
It's a rather small class, mapping the image parsefile to its user.
In beforeSave, I get the user, increment his imageCount, save the user, get the imageCount out of the user, add it to the image, save the image and add a flag to the user if he has 20 images, then save him, too.
My fix is now doing all of this in afterSave which doesn't seem to break but that way I double the api requests since I have to save the image twice.

What makes this even more annoying is the fact, that the user ends up with only 19 images and has to restart the whole learning process (the app thinks its an network issue), so I end up losing him alltogether. At least a quick workaround to retry this specific exception would be appreciated.
