### ISSUE TITLE
Logged in current user disappears after refresh or redirect

### ISSUE THREAD

**Issue by arteriespeter** [ParsePlatform/Parse-SDK-JS#84]
In Firefox or Chrome clear all the history (cache and cookie data) before checking this issue.

Logging in with this JS:
```javascript
    Parse.User.logIn($("#uname").val(), $("#upass").val()).then(function (user) {
        console.log("login ok", user);
        $("#loginform").submit();
        //window.location = "/main";
    }, function (error) {});
```
This code gives back the user. But after submitting the form (that performs a login in node.js too), or just window.location change, the `Parse.User.current()` is empty (null).

We make a logout (with nobody), then the second login attempt works, the current() method gives the user data.

I thought that it is not necessary to perform a login in node.js but if it is missing, the `Parse.User.current()` is null there too.

**Comment by andrewimm** [comment]
I'll need more information to better understand the issue here. Ideally, if you could produce a minimal, reproducible test case that we could verify, we'd be able to better debug this.

If you remove the part involving Node.js, you say that logging in and refreshing the page results in the current user not being set. Is that correct?

This is a difficult issue to resolve, since we don't ship any SDKs without running them through a series of tests that check, among other things, exactly this scenario -- logging in, refreshing the page, and checking that the user is still stored in local storage.

**Comment by arteriespeter** [comment]
Hello, you can debug it with this simple app.
https://budlogintest.parseapp.com

user: peter+test@arteries.hu
pass: test

This user has an "EditorRole" role.

Steps:
Login first time and check the console, run Parse.User.current() after redirect. It will be null.
Logout.
Login second time, then check Parse.User.current() gives back the user.

You can find the code here:
http://goo.gl/iW62Or

**Comment by andrewimm** [comment]
I was unable to reproduce. Doing the actions you outlined, I was able to verify that the user was stored in localStorage, and it continued to be fetched after refreshing the page.

**Comment by arteriespeter** [comment]
Please check this video how I reached this situation.
http://goo.gl/DR2O3Q
The problem is that it behaves same on the production site, but there we don't clear the history. Next day we have this issue, they have to login 2 times.
