### ISSUE TITLE
Parse.initialize is global and wont work with multiple accounts/environments

### ISSUE THREAD

**Issue by arethtapslots** [ParsePlatform/Parse-SDK-JS#85]
When I do a var Parse = require('parse/node'); then a Parse.initialize(applicationId, javascriptKey, masterKey), this sets the applicationId, js key and masterkey for one account, but if I wanted to do Parse.initialize on other accounts, is that possible at all using this npm module? It seems like it only works for one Parse environment. If it is possible, how can I do that? I would like to query different parse accounts, since we have a dev, qa and prod environment. Thanks.

**Comment by wangmengyan95** [comment]
Hi @arethtapslots, you can but we do not recommend to do that. When you call `Parse.initialize(applicationId, javascriptKey, masterKey)`, we actually use the info you provide as headers of each request we send to Parse. Since Parse is asynchronous, if you call `Parse.initialize(applicationId, javascriptKey, masterKey)` multiple times, it is possible that some request which should use the old app info actually use the new app info. In this situation, those requests will fail and there is no good way to handle that. For your case, I am curious why you do not judge your env at the beginning and initialize different parse app? Hope it helps.

**Comment by arethtapslots** [comment]
Well I want one nodejs app that can connect to different environments. Each parse app is a different environment, one is dev, one is qa and one is production. I'm making an interface that can query each different environment based on the users choice of environment. I think I have to use the Rest API instead of this module to achieve this. Unless there is a way to make separate instances with this module, it doesn't seem to be possible as of now.

**Comment by andrewimm** [comment]
The SDK does not support multiple instances at this time, since that would require a number of major API changes, and would introduce some serious points of developer confusion. For instance, a Parse.Object from one instance would be wholly incompatible with Parse.Objects from another instance, making a number of internal and external interfaces behave unpredictably. This is such a rare use case, and introduces such internal complexity, that we do not see this as a viable change at this time.

I recommend directly communicating with the REST API, as you mentioned.

**Comment by smshuja** [comment]
@andrewimm Recently I had to drop Parse because of this. My requirement was like that of shared containers provided by CloudKit.
