### ISSUE TITLE
Parse.Query doesn't return instances of ES6 classes

### ISSUE THREAD

**Issue by myuller** [ParsePlatform/Parse-SDK-JS#88]
```javascript
class Child extends Parse.Object {
  constructor() {
    super("Child");
  }
}
new Parse.Query(Child).find().then((children) = {
  if (children.length > 0) {
    console.log(children[0] instanceof Child); // prints "false"
  }
});
```

Works when Child is specified with old Parse.Object.extend syntax

**Comment by oriSomething** [comment]
what your showing is problematic. because `Parse.Query` cannot magically access this `class` that you created by this syntax. also if you'll have two declaration of the same `class Child extends Parse.Object {···}` JavaScript won't treat instance of one of them of the other. it's part of the way JavaScript works.
As everything else in JavaScript, it would advice to use duck typing checking:
```js
children && children[0] && children[0].className === 'Child'
```

**Comment by TylerBrock** [comment]
When using es6 classes to extend Parse.Object you must register the subclass: `Parse.Object.registerSubclass("className", constructor)`

Just have a registration follow the class declaration:

```js
class Child extends Parse.Object {
  constructor(attributes, options) {
    super("Child", attributes, options);
  }
}
Parse.Object.registerSubclass('Child', Child);
```

**Comment by wangmengyan95** [comment]
Hi @myuller, we maintain an inner classMap to keep track of all subclasses of ParseObjct. When objects of a subclass are retrieved from a query, if we can find the subclass in the classMap, the objects will be instantiated with this subclass. In order to use the subclass in es6, you have to manually call `registerSubclass `. For es5, we have done that for you in `extend`, check [here](https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/ParseObject.js#L1427).
Thanks for your awesome explanation @TylerBrock.

**Comment by myuller** [comment]
@TylerBrock @wangmengyan95 Thank you!
